config/routes.rb
Rails.application.routes.draw do
  resources :subitems
  resources :subitem_categories
  resources :subitem_fields
  resources :shipment_informations
  resources :category_field_values
  resources :items
  resources :category_fields
  resources :fields
  resources :categories
  
  get '/account', to: 'personal_account#index' , as: :account
  get '/account/orders_history', to: 'personal_account#show_orders_history' , as: :account_orders
  get '/account/show_order/:order_id', to: 'personal_account#show_order' , as: :account_show_order
  get '/orders_management', to: 'orders#show_orders' , as: :orders_management
  get '/home', to: 'home#index', as: :home
  get '/administration', to: 'administrator_panel#index' , as: :administration
  get '/administration/users', to: 'administrator_panel#all_users' , as: :administration_users
  get '/administration/user_info/:user_id', to: 'administrator_panel#show_user_info' , as: :administration_user_info
  

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#catalog"

  get '/item_category_fields/:item_id/:category_id', to: 'category_fields#item_category_fields', as: :item_category_fields
  get '/catalog(/:category_id)', to: 'items#catalog', as: :catalog_category
  get '/sub_catalog(/:category_id)', to: 'subitems#catalog', as: :sub_catalog_category


  post '/account/reorder/:order_id', to: 'orders#reorder' , as: :reorder
  post '/cart/add_item_with_subitems/:item_id', to: 'cart#add_item_with_subitems', as: :cart_add_item_with_subitems
  get '/cart', to: 'cart#index', as: :cart
  post '/cart/add_item/:item_id', to: 'cart#add_item', as: :cart_add_item
  post '/cart/update_subitems/:order_item_id', to: 'cart#update_subitems', as: :cart_update_subitem
  delete '/cart/delete_item/:item_id', to: 'cart#delete_item', as: :cart_delete_item
  delete '/cart/delete_subitem/:order_subitem_id', to: 'cart#delete_subitem', as: :cart_delete_subitem
  put '/cart/increment_item_count/:item_id', to: 'cart#increment_item_count', as: :cart_increment_item_count
  put '/cart/decrement_item_count/:item_id', to: 'cart#decrement_item_count', as: :cart_decrement_item_count

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent_category, :foreign_key => 'parent_category_id', class_name: "Category", optional: true
  has_many :category_fields, dependent: :delete_all
  has_many :items, dependent: :nullify
  has_many :subitem_item_categories

  accepts_nested_attributes_for :category_fields, reject_if: :all_blank, allow_destroy: true
end

app/models/category_field.rb
class CategoryField < ApplicationRecord
  belongs_to :category
  belongs_to :field
  has_many :category_field_values, dependent: :delete_all

  def get_item_field(item_id)
    self.category_field_values.select { |cfv| cfv.item_id == item_id }.first
  end
end

app/models/field.rb
class Field < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :subitems_for_category
  has_many :selected_subitems
  accepts_nested_attributes_for :selected_subitems, reject_if: :all_blank, allow_destroy: true

  has_attached_file :image, styles: { high: "840x600>", medium: "280x200>", thumb: "140x100>" },
    default_url: ":style/missing_item_image.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def price_formatted
    return self.price.to_s.reverse.gsub(/...(?=.)/,'\& ').reverse
  end

  def fixed_length_description
    if self.description&.length > 60
      return self.description[0..60] + '..'
    else
      return self.description
    end
  end

  def selected_subitems
    Subitem.none
  end

  def subitems_for_category
    # @subitems = []
    # @subitem_items = SubitemItemCategory.where(category_id: self.category_id)

    # @subitem_items.each do |s|
    #   @subitems.push(Subitem.find(s.subitem_id))
    # end

    Subitem.joins("INNER JOIN subitem_item_categories ON subitems.id = subitem_item_categories.subitem_id").where(subitem_item_categories: {category_id: self.category_id})
  end

end

app/models/juristic_document.rb
class JuristicDocument < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :delete_all

  enum status: { cart: 0, ordered: 1, payed: 2, completed: 3 }

  def get_items
    self.order_items.order(:id)
  end

  def add_item(item_id, count)
    order_item = self.order_items.create(item_id: item_id, count: 1)
  end


  def update_subitems(order_item_id, subitems)
    OrderItem.find(order_item_id)&.update(subitems) if subitems
  end

  # @param [Hash] subitems - hash('0'=>{:id, ..},1=>{:id, ..},..)
  def add_item_with_subitems(item_id, count, subitems)
    order_item = self.order_items.create(item_id: item_id, count: 1)

    # add subitems to order_item
    subitems.each do |key, subitem|
      item_subitems = order_item.order_item_subitems.create(
        order_item_id: order_item.id,
        subitem_id: subitem[:id],
        count: 1
      )
    end
  end

  def delete_item(item_id)
    self.order_items.find_by(item_id: item_id)&.destroy
    self.save
  end

  def delete_subitem(order_subitem_id)
    OrderItemSubitem.delete(order_subitem_id)
  end

  def increment_item_count(item_id)
    order_item = self.order_items.find_by(item_id: item_id)
    order_item&.count += 1
    order_item&.save
  end

  def decrement_item_count(item_id)
    order_item = self.order_items.find_by(item_id: item_id)
    return if order_item&.count <= 1
    order_item&.count -= 1
    order_item&.save
  end

  def set_item_count(item_id, count)
    order_item = self.order_items.find_by(item_id: item_id)
    order_item&.count = count
    order_item&.save
  end

  def clear
    self.order_items.destroy_all
    self.save
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  has_many :order_item_subitems, dependent: :delete_all

  alias_attribute :order_subitems, :order_item_subitems
  accepts_nested_attributes_for :order_item_subitems, reject_if: :all_blank, allow_destroy: true
  
end

app/models/order_item_subitem.rb
class OrderItemSubitem < ApplicationRecord
  belongs_to :subitem
  belongs_to :order_item
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/subitem.rb
class Subitem < ApplicationRecord
  belongs_to :subitem_category
  has_many :subitem_item_categories

  accepts_nested_attributes_for :subitem_item_categories, reject_if: :all_blank, allow_destroy: true


end

app/models/subitem_category.rb
class SubitemCategory < ApplicationRecord
end

app/models/subitem_field.rb
class SubitemField < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    return self.role == '1'
  end
  has_one :payment_information
  has_one :juristic_document
  has_many :shipment_informations
end

app/controllers/personal_account_controller.rb
class PersonalAccountController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = current_user
		@paymnt_data = PaymentInformation.find(@user.payment_information_id)
		@juristic_data = JuristicDocument.find(@user.juristic_document_id)
		@shipment_info = ShipmentInformation.where(user_id: @user.id)
	end

	def show_orders_history
		@user = current_user
		@orders = Order.where(status: 'cart')
	end

	def show_order
		@order = Order.find(params[:order_id])
		@order_items = OrderItem.where(order_id: @order.id)		
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/personal_account_helper.rb
module PersonalAccountHelper
end

app/helpers/subitems_helper.rb
module SubitemsHelper
end

app/views/personal_account/_user_info.html.slim
.uk-text-left 
  h3 Личные данные    
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Имя:         
      span.text =@user.first_name 
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Фамилия:
      span.text =@user.last_name
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Отчество:
      span.text =@user.middle_name
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text email:
      span.text =@user.email  

.uk-text-left 
  h3 Платежные данные    
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Расчетный счет:         
      span.text =@paymnt_data&.payment_account 
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Полное наименование банка:
      span.text =@paymnt_data&.bank_name
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text БИК:
      span.text =@paymnt_data&.bik
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Корреспондентский счет банка:
      span.text =@paymnt_data&.bank_correspondent_account    

.uk-text-left 
  h3 Юридическая информация    
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Полное наименование организации:         
      span.text =@juristic_data&.company_full_name 
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Краткое наименование организации:
      span.text =@juristic_data&.company_short_name
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Генеральный директор:
      span.text =@juristic_data&.ceo_name
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Юридический адрес:
      span.text =@juristic_data&.legal_address        
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text Почтовый адрес:
      span.text =@juristic_data.postal_address        
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text ИНН:
      span.text =@juristic_data&.inn        
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text КПП:
      span.text =@juristic_data&.kpp
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text ОГРН:
      span.text =@juristic_data&.ogrn
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text ОКПО:
      span.text =@juristic_data&.okpo
  .uk-width-1-1.uk-inline.uk-margin-small-bottom      
      span.uk-label
        span.text ОКАТО:
      span.text =@juristic_data&.okato

app/views/personal_account/index.html.slim
= render 'user_info'

=< link_to 'История покупок', account_orders_path, class: 'uk-button uk-button-emerald uk-margin-top'

=< link_to 'Изменить данные', edit_user_registration_path, class: 'uk-button uk-button-emerald uk-margin-top'

=< link_to 'Изменить данные доставки', shipment_informations_path, class: 'uk-button uk-button-emerald uk-margin-top'

app/views/personal_account/show_order.html.slim
- @order_items.each do |order_item| 
  tr   
  	=< link_to 'Повторный заказ', reorder_path, method: :post, class: 'uk-button uk-button-emerald uk-margin-top'

  	br

    td
      = order_item.item_id
    br
    td 
      = order_item.count
    br
	td	 
	  = order_item.price
	
	div Subitems:

	-order_item.order_item_subitems.each do |subitem|
	  tr
	  	td 
	  	  = subitem.subitem_id
	  	br
	  	td 
	      = subitem.count
	    br
		td 
		  = subitem.price

app/views/personal_account/show_orders_history.html.slim
- @orders.each do |order|
  tr   
    td
      = link_to "#{order.id} #{order.ordered_date} #{order.status}", account_show_order_path(order.id)
    br