config/routes.rb
Rails.application.routes.draw do
  resources :subitems
  resources :subitem_categories
  resources :subitem_fields
  resources :shipment_informations
  resources :category_field_values
  resources :items
  resources :category_fields
  resources :fields
  resources :categories
  
  get '/account', to: 'personal_account#index' , as: :account
  get '/account/orders_history', to: 'personal_account#show_orders_history' , as: :account_orders
  get '/account/show_order/:order_id', to: 'personal_account#show_order' , as: :account_show_order
  get '/orders_management', to: 'orders#show_orders' , as: :orders_management
  get '/home', to: 'home#index', as: :home
  get '/administration', to: 'administrator_panel#index' , as: :administration
  get '/administration/users', to: 'administrator_panel#all_users' , as: :administration_users
  get '/administration/user_info/:user_id', to: 'administrator_panel#show_user_info' , as: :administration_user_info
  

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#catalog"

  get '/item_category_fields/:item_id/:category_id', to: 'category_fields#item_category_fields', as: :item_category_fields
  get '/catalog(/:category_id)', to: 'items#catalog', as: :catalog_category
  get '/sub_catalog(/:category_id)', to: 'subitems#catalog', as: :sub_catalog_category


  post '/account/reorder/:order_id', to: 'orders#reorder' , as: :reorder
  post '/cart/add_item_with_subitems/:item_id', to: 'cart#add_item_with_subitems', as: :cart_add_item_with_subitems
  get '/cart', to: 'cart#index', as: :cart
  post '/cart/add_item/:item_id', to: 'cart#add_item', as: :cart_add_item
  post '/cart/update_subitems/:order_item_id', to: 'cart#update_subitems', as: :cart_update_subitem
  delete '/cart/delete_item/:item_id', to: 'cart#delete_item', as: :cart_delete_item
  delete '/cart/delete_subitem/:order_subitem_id', to: 'cart#delete_subitem', as: :cart_delete_subitem
  put '/cart/increment_item_count/:item_id', to: 'cart#increment_item_count', as: :cart_increment_item_count
  put '/cart/decrement_item_count/:item_id', to: 'cart#decrement_item_count', as: :cart_decrement_item_count

end

app/models/subitem.rb
class Subitem < ApplicationRecord
  belongs_to :subitem_category
  has_many :subitem_item_categories

  accepts_nested_attributes_for :subitem_item_categories, reject_if: :all_blank, allow_destroy: true


end

app/controllers/subitems_controller.rb
class SubitemsController < ApplicationController
  before_action :set_subitem, only: [:show, :edit, :update, :destroy]

  # GET /subitems
  # GET /subitems.json
  def index
    @subitems = Subitem.all
  end

  # GET /subitems/1
  # GET /subitems/1.json
  def show
  end


  def catalog
     @child_categories = {}
     @all_categories = Category.all
     @head_categories = @all_categories.select { |cat| cat.parent_category_id.nil? }
     @all_categories.each do |cat|
      if !cat.parent_category_id.nil?
        if @child_categories[cat.parent_category_id].nil?
          @child_categories[cat.parent_category_id] = [cat]
        else
          @child_categories[cat.parent_category_id] << cat
        end
      end
    end
    @subitems = Subitem.all
  end
  # GET /subitems/new
  def new
    @subitem = Subitem.new
  end

  # GET /subitems/1/edit
  def edit
  end

  # POST /subitems
  # POST /subitems.json
  def create
    @subitem = Subitem.new(subitem_params)

    respond_to do |format|
      if @subitem.save
        format.html { redirect_to @subitem, notice: 'Subitem was successfully created.' }
        format.json { render :show, status: :created, location: @subitem }
      else
        format.html { render :new }
        format.json { render json: @subitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subitems/1
  # PATCH/PUT /subitems/1.json
  def update
    respond_to do |format|
      #params[:subitem][:subitem_category_id] = subitem_cat_params[:id]
      #puts params[:subitem][:subitem_category_id]
      if @subitem.update(subitem_params)
        format.html { redirect_to @subitem, notice: 'Subitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @subitem }
      else
        format.html { render :edit }
        format.json { render json: @subitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subitems/1
  # DELETE /subitems/1.json
  def destroy
    @subitem.destroy
    respond_to do |format|
      format.html { redirect_to subitems_url, notice: 'Subitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subitem
      @subitem = Subitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subitem_params
      params.require(:subitem).permit(:name, :description, :price, :subitem_category_id, subitem_item_categories_attributes: [:id, :subitem_id, :category_id, :_destroy])
    end

    # def subitem_cat_params
    #   params.require(:subitem).permit(:id, )
    # end
end

app/helpers/subitems_helper.rb
module SubitemsHelper
end

app/views/subitems/_form.html.slim
= form_for(subitem) do |f|
  - if subitem.errors.any?
    #error_explanation
      h2
        = pluralize(subitem.errors.count, "error")
        |  prohibited this subitem from being saved:
      ul
        - subitem.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    = f.text_area :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .field
    -@subitems_cats = Category.where(is_leaf: true)
    = f.fields_for :subitem_item_categories do |subitem|
      / = subitem.select(:id, @subitems_cats.map{ |t| [t.name, t.id] }, {}, class: "form-control")      
      = render 'subitem_item_category_fields', f: subitem
    .links
      = link_to_add_association "Добавить поле".html_safe, f, :subitem_item_categories
  .actions
    = f.submit

app/views/subitems/_subitem_item_category_fields.html.slim
.nested-fields
  .form-group
    / = @subitem&.name
    br
    .input-group      
      = f.select(:category_id, @subitems_cats.map{ |t| [t.name, t.id] }, {}, class: "form-control") 
      span.input-group-btn      	
        = link_to_remove_association "Удалить".html_safe, f, class: "btn btn-danger btn-sm"

app/views/subitems/catalog.html.slim
.uk-grid.uk-grid-medium
  aside
    h3 Каталог продукции
    ul.tm-list-category.uk-margin-remove uk-accordion=("multiple: true") 
      - @head_categories.each_with_index do |cat, index|
        - if cat.id == @side_opened_category_id || (@side_opened_category_id.nil? && index == 0)
          li.uk-open
            h4.uk-accordion-title = cat.name
            .uk-accordion-content.uk-margin-remove
              ul
                - @child_categories[cat.id].each do |subcat| 
                  li
                    = link_to subcat.name, catalog_category_path(subcat.id)
        - else
          li
            h4.uk-accordion-title = cat.name
            .uk-accordion-content.uk-margin-remove
              ul
                - @child_categories[cat.id].each do |subcat| 
                  li
                    = link_to subcat.name, catalog_category_path(subcat.id)   
      li
        = link_to sub_catalog_category_path
          h4.uk-accordion-title  Дополнительное оборудование
          
  .uk-width-expand
    ul.uk-subnav.uk-subnav-pill.tm-product-swbutton uk-switcher="animation:uk-animation-fade;connect:.tm-product-switch" 
      li
        a href="#"  Новинки
      li
        a href="#"  Под заказ
      li
        a href="#"  Скидки
    .uk-switcher.tm-product-switch.uk-margin
      .uk-grid-small class="uk-child-width-1-4@l" uk-grid="" 
        - @subitems.each do |subitem|
          .product
            .wrapper
              = link_to subitem_path(subitem) , class: 'href'  
                = subitem.name             
                .stars
                  span
                  span
                  span
                  span.grey
                  span.grey
                  | (3)
              .info                
                .introtext = subitem.description
                .price
                  | от
                  span = subitem.price
                  sup руб.

app/views/subitems/edit.html.slim
h1
  | Editing Subitem
= render 'form', subitem: @subitem
= link_to 'Show', @subitem
|  | 
= link_to 'Back', subitems_path

app/views/subitems/index.html.slim
p#notice
  = notice
h1
  | Subitems
table
  thead
    tr
      th
        | Name
      th
        | Description
      th
        | Price
      th
        | Subitem category
      th[colspan="3"]
  tbody
    - @subitems.each do |subitem|
      tr
        td
          = subitem.name
        td
          = subitem.description
        td
          = subitem.price
        td
          = subitem.subitem_category
        td
          = link_to 'Show', subitem
        td
          = link_to 'Edit', edit_subitem_path(subitem)
        td
          = link_to 'Destroy', subitem, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Subitem', new_subitem_path

app/views/subitems/new.html.slim
h1
  | New Subitem
= render 'form', subitem: @subitem
= link_to 'Back', subitems_path

app/views/subitems/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @subitem.name
p
  strong
    | Description:
  = @subitem.description
p
  strong
    | Price:
  = @subitem.price
p
  strong
    | Subitem category:
  = @subitem.subitem_category.name
= link_to 'Edit', edit_subitem_path(@subitem)
|  | 
= link_to 'Back', subitems_path