config/routes.rb
Rails.application.routes.draw do
  resources :subitems
  resources :subitem_categories
  resources :subitem_fields
  resources :shipment_informations
  resources :category_field_values
  resources :items
  resources :category_fields
  resources :fields
  resources :categories
  
  get '/account', to: 'personal_account#index' , as: :account
  get '/account/orders_history', to: 'personal_account#show_orders_history' , as: :account_orders
  get '/account/show_order/:order_id', to: 'personal_account#show_order' , as: :account_show_order
  get '/orders_management', to: 'orders#show_orders' , as: :orders_management
  get '/home', to: 'home#index', as: :home
  get '/administration', to: 'administrator_panel#index' , as: :administration
  get '/administration/users', to: 'administrator_panel#all_users' , as: :administration_users
  get '/administration/user_info/:user_id', to: 'administrator_panel#show_user_info' , as: :administration_user_info
  

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#catalog"

  get '/item_category_fields/:item_id/:category_id', to: 'category_fields#item_category_fields', as: :item_category_fields
  get '/catalog(/:category_id)', to: 'items#catalog', as: :catalog_category
  get '/sub_catalog(/:category_id)', to: 'subitems#catalog', as: :sub_catalog_category


  post '/account/reorder/:order_id', to: 'orders#reorder' , as: :reorder
  post '/cart/add_item_with_subitems/:item_id', to: 'cart#add_item_with_subitems', as: :cart_add_item_with_subitems
  get '/cart', to: 'cart#index', as: :cart
  post '/cart/add_item/:item_id', to: 'cart#add_item', as: :cart_add_item
  post '/cart/update_subitems/:order_item_id', to: 'cart#update_subitems', as: :cart_update_subitem
  delete '/cart/delete_item/:item_id', to: 'cart#delete_item', as: :cart_delete_item
  delete '/cart/delete_subitem/:order_subitem_id', to: 'cart#delete_subitem', as: :cart_delete_subitem
  put '/cart/increment_item_count/:item_id', to: 'cart#increment_item_count', as: :cart_increment_item_count
  put '/cart/decrement_item_count/:item_id', to: 'cart#decrement_item_count', as: :cart_decrement_item_count

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :subitems_for_category
  has_many :selected_subitems
  accepts_nested_attributes_for :selected_subitems, reject_if: :all_blank, allow_destroy: true

  has_attached_file :image, styles: { high: "840x600>", medium: "280x200>", thumb: "140x100>" },
    default_url: ":style/missing_item_image.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def price_formatted
    return self.price.to_s.reverse.gsub(/...(?=.)/,'\& ').reverse
  end

  def fixed_length_description
    if self.description&.length > 60
      return self.description[0..60] + '..'
    else
      return self.description
    end
  end

  def selected_subitems
    Subitem.none
  end

  def subitems_for_category
    # @subitems = []
    # @subitem_items = SubitemItemCategory.where(category_id: self.category_id)

    # @subitem_items.each do |s|
    #   @subitems.push(Subitem.find(s.subitem_id))
    # end

    Subitem.joins("INNER JOIN subitem_item_categories ON subitems.id = subitem_item_categories.subitem_id").where(subitem_item_categories: {category_id: self.category_id})
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :is_admin!, only: [:index, :edit, :update, :destroy]
  # before_action :is_admin!
  # GET /items
  # GET /items.json
  def index
    @items = Item.all.order(:id)
  end

  # GET /catalog(/:category_id)
  def catalog
    if params[:category_id]
      category = Category.find(params[:category_id])
      if category
        @side_opened_category_id = category.parent_category_id
        @current_category_id = category.id
        @items = Item.where(category_id: @current_category_id)
      end
    end

    @items ||= Item.all.order(:id) # If no category

    @child_categories = {}
    @all_categories = Category.all
    @head_categories = @all_categories.select { |cat| cat.parent_category_id.nil? }
    @all_categories.each do |cat|
      if !cat.parent_category_id.nil?
        if @child_categories[cat.parent_category_id].nil?
          @child_categories[cat.parent_category_id] = [cat]
        else
          @child_categories[cat.parent_category_id] << cat
        end
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @field_values = CategoryFieldValue.joins(:category_field).where(item_id: @item.id, category_fields: { category_id: @item.category_id }).all.select{ |fv| !fv.category_field.nil? }

    @available_subitems = @item.subitems_for_category  

  end

  # GET /items/new
  def new
    @item = Item.new
    @category_fields = CategoryField.where(category_id: Category.first).all
  end

  # GET /items/1/edit
  def edit
      # @field_values = CategoryFieldValue.where(item_id: @item.id).all.select{ |fv| !fv.category_field.nil? }
      @category_fields = CategoryField.where(category_id: @item.category_id).all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        category_field_values = []
        params[:item_field].each do |key, value|
          category_field_values << { item_id: @item.id, category_field_id: key, value: value }
        end
        CategoryFieldValue.create(category_field_values)
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    # abort params[:item_field].inspect
    # abort params[:id].inspect

    respond_to do |format|
      if @item.update(item_params)
        params[:item_field].each do |key, value|
          cfv = CategoryFieldValue.where(item_id: params[:id], category_field_id: key).first
          if cfv.nil?
            CategoryFieldValue.create(item_id: params[:id], category_field_id: key, value: value)
          else
            if cfv.value != value
              cfv.value = value
              cfv.save
            end
          end
        end
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :category_id, :price, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= render 'administrator_panel/sidebar'
= form_for(item, html: { multipart: true }) do |f|
  - if item.errors.any?
    #error_explanation
      h2
        = pluralize(item.errors.count, "error")
        |  prohibited this item from being saved:
      ul
        - item.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :category_id
    = f.select(:category_id, Category.all.select{ |t| t.is_leaf }.map{ |t| [t.name, t.id] }, {}, class: "form-control")
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :image
    - if item.image.present?
      = image_tag item.image.url(:medium), height:'200', width: '280', alt: ''
      br
      |  (Текущая картинка)
    - else
      br
      |  Картинка не установлена, будет использована стандартная
      br
    = f.file_field :image
  
  p
    input#item-id-input [type="hidden" value="#{item.id ? item.id : 0}"]
    strong
      | Fields:
    br
    #fields
      - @category_fields&.each do |category_field|
        - @cfv = category_field.get_item_field(item.id)
        input [name="item_field[#{category_field.id}]" value="#{@cfv&.value}"]
        br
  .actions
    = f.submit

app/views/items/_selected_subitem_fields.html.slim
.nested-fields
  .form-group
    / = @subitem&.name
    br
    .input-group      
      = f.select(:id, @available_subitems.map{ |t| [t.name, t.id] }, {}, class: "form-control")
      span.input-group-btn      	
        = link_to_remove_association "Удалить".html_safe, f, class: "btn btn-danger btn-sm"

app/views/items/_subitems_for_category_fields.html.slim
.nested-fields
  .form-group
    / = @subitem&.name
    br
    .input-group
      = f.select(:id, @subitems.map{ |t| [t.name, t.id] }, {}, class: "form-control")
      span.input-group-btn
        = link_to_remove_association "Удалить".html_safe, f, class: "btn btn-danger btn-sm"

app/views/items/catalog.html.slim
.uk-grid.uk-grid-medium
  aside
    h3 Каталог продукции
    ul.tm-list-category.uk-margin-remove uk-accordion=("multiple: true") 
      - @head_categories.each_with_index do |cat, index|
        - if cat.id == @side_opened_category_id || (@side_opened_category_id.nil? && index == 0)
          li.uk-open
            h4.uk-accordion-title = cat.name
            .uk-accordion-content.uk-margin-remove
              ul
                - @child_categories[cat.id].each do |subcat| 
                  li
                    = link_to subcat.name, catalog_category_path(subcat.id)
        - else
          li
            h4.uk-accordion-title = cat.name
            .uk-accordion-content.uk-margin-remove
              ul
                - @child_categories[cat.id].each do |subcat| 
                  li
                    = link_to subcat.name, catalog_category_path(subcat.id)
              ul                
                = link_to 'Дополнительное оборудование', sub_catalog_category_path
                    
    ul.tm-list-leader.uk-list
      li
        a href="#" 
          span.badge.new
            i uk-icon=("icon: tag; ratio: 1") 
          | Новинки
      li
        a href="#" 
          span.badge.hit
            i uk-icon=("icon: future; ratio: 0.8") 
          | Под заказ
      li
        a href="#" 
          span.badge.discount> %
          | Скидки
  .uk-width-expand
    ul.uk-subnav.uk-subnav-pill.tm-product-swbutton uk-switcher="animation:uk-animation-fade;connect:.tm-product-switch" 
      li
        a href="#"  Новинки
      li
        a href="#"  Под заказ
      li
        a href="#"  Скидки
    .uk-switcher.tm-product-switch.uk-margin
      .uk-grid-small class="uk-child-width-1-4@l" uk-grid="" 
        - @items.each do |item|
          .product
            .wrapper
              = link_to item_path(item), class: 'image'
                = image_tag item.image.url(:medium), height:'200', width: '280', alt: ''
                .stars
                  span
                  span
                  span
                  span.grey
                  span.grey
                  | (3)
              .info
                = link_to item.name, item_path(item), class: 'href'
                .introtext = item.description
                .price
                  | от
                  span = item.price_formatted
                  sup руб.
                .icons.uk-child-width-1-3.uk-grid-collapse uk-grid="" 
                  div
                    img alt="Шасси" src="#{image_url 'awesome/02_shassi.svg'}" /
                    span 6 x 4
                  div
                    img alt="Грузоподъемность" src="#{image_url 'awesome/02_weight.svg'}" /
                    span 20 т.
                  div
                    img alt="Бензин" src="#{image_url 'awesome/02_benzin.svg'}" /
                    span Евро 4
                .buttons.uk-child-width-1-3.uk-grid-collapse uk-grid="" 
                  = link_to cart_add_item_path(item), method: :post, class: 'uk-button', title: 'Добавить в Корзину'
                    span.cart
                  a.uk-button href="" title=("Добавить в Закладки") 
                    span.heart
                  a.uk-button href="" title=("Перейти к Товару") 
                    span.goproduct
        
      div
        | 2
      div
        | 3

app/views/items/edit.html.slim
= render 'administrator_panel/sidebar'
h1
  | Изменение товара
= render 'form', item: @item
= link_to 'Показать', @item
|  | 
= link_to 'Назад', items_path

app/views/items/index.html.slim
h1
  | Товары
table.uk-table.uk-table-striped
  thead
    tr
      th
        | Название
      th
        | Описание
      th
        | Категория
      th
        | Цена
      th[colspan="3"]
  tbody
    - @items&.each do |item|
      tr
        td
          = item.name
        td
          = item.fixed_length_description
        td
          = item.category&.name
        td
          = item.price
        td
          => link_to 'Показать', item
          | /
          =<> link_to 'Изменить', edit_item_path(item)
          | /
          =< link_to 'Удалить', item, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить товар?' }
br
= link_to 'Создать товар', new_item_path

app/views/items/new.html.slim
h1
  | Новый товар
= render 'form', item: @item
= link_to 'Назад', items_path

app/views/items/show.html.slim
.main.uk-container-small
  .uk-grid
    .uk-width-1-2
      = image_tag @item.image.url(:high), width: '100%', alt: ''
    .uk-width-1-2
      h2 = @item.name
      .uk-text-small
        = @item.category.name
      .item-description
        = @item.description
      .item-price
        | от
        =<> @item.price
        | руб.
      br
      .fields
        strong
          | Характеристики:
        br
        - @field_values&.each do |field_value|
          = "#{field_value.field&.name}: #{field_value.value}"
          br
      - if current_user&.is_admin?
        = link_to 'Edit', edit_item_path(@item)
      br      
      #field
        = form_for(@item, url: cart_add_item_with_subitems_path(@item.id), method: :post,  html: { multipart: true }) do |f|
          = f.label :selected_subitems, "Доп. оборудование", class: "control-label"
          div
            = f.fields_for :selected_subitems do |subitem|               
              = render 'selected_subitem_fields', f: subitem
            .links
              = link_to_add_association "Добавить поле".html_safe, f, :selected_subitems
          button Добавить в корзину

      - if current_user&.is_admin?
        = link_to 'Edit', edit_item_path(@item)  

      